apiVersion: v1
kind: Secret
metadata:
  name: kes-configuration
  namespace: minio-tenant-1
type: Opaque
stringData:
  server-config.yaml: |-
    version: v1
    address: :7373
    admin:
      identity: _ # Effectively disabled since no root identity necessary.
    tls:
      key: /tmp/kes/server.key   # Path to the TLS private key
      cert: /tmp/kes/server.crt # Path to the TLS certificate
      proxy:
        identities: []
        header:
          cert: X-Tls-Client-Cert
    policy:
      my-policy:
        allow:
        - /v1/api
        - /v1/key/create/*
        - /v1/key/generate/*
        - /v1/key/decrypt/*
        - /v1/key/bulk/decrypt/*
        - /v1/metrics
        identities:
        - ${MINIO_KES_IDENTITY} 
    cache:
      expiry:
        any: 5m0s
        unused: 20s
    log:
      error: on
      audit: off
    keystore:
      vault:
        endpoint: "http://vault.minio-tenant-1.svc.cluster.local:8200" # The Vault endpoint
        namespace: "" # An optional Vault namespace. See: https://www.vaultproject.io/docs/enterprise/namespaces/index.html
        prefix: "my-minio"    # An optional K/V prefix. The server will store keys under this prefix.
        approle:    # AppRole credentials. See: https://www.vaultproject.io/docs/auth/approle.html
          id: "c2346475-0cb7-bfbb-ad96-8cca22016736"      # Your AppRole Role ID
          secret: "ce675703-ae2b-006e-2039-67d68437eb69"  # Your AppRole Secret ID
          retry: 15s  # Duration until the server tries to re-authenticate after connection loss.
        tls:        # The Vault client TLS configuration for mTLS authentication and certificate verification
          key: ""     # Path to the TLS client private key for mTLS authentication to Vault
          cert: ""    # Path to the TLS client certificate for mTLS authentication to Vault
          ca: ""      # Path to one or multiple PEM root CA certificates
        status:     # Vault status configuration. The server will periodically reach out to Vault to check its status.
          ping: 10s   # Duration until the server checks Vault's status again.
