apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-cluster-role.yaml
  - prometheus-cluster-role-binding.yaml
  - prometheus-service-account.yaml
  - kes-scrape-config.yaml
  - prometheus.yaml