apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: minio-tenant-1
  labels:
    prometheus: prometheus
spec:
  replicas: 2
  serviceAccountName: prometheus
  scrapeConfigSelector:
    matchLabels:
      prometheus: kes-monitoring-prometheus
